version: '3'
services:
  fim-backend:
    image: fim-backend:1.0
    container_name: fim-backend
    volumes:
      - /var/docker_volumes/fim-backend:/var/fim-backend/
    restart: always
    ports:
      - "8080:8080"
networks:
  default:
    external:
      name: fim-network